config/routes.rb
Rails.application.routes.draw do
  resources :cocktails, only: [:index, :show, :new, :create] do
    resources :doses, only: [:new, :create]
  end
 resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :ingredient
  belongs_to :cocktail
  validates :description, presence: true
  validates :cocktail_id, uniqueness: {scope: :ingredient_id}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only:[:show]

  def index
    @cocktails = Cocktail.all
  end

  def show
    # set_cocktail, gives us the cocktail found by id
    @doses = @cocktail.doses
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
before_action :set_cocktail, except: :destroy

  def new
    puts params
    @dose = Dose.new
  end

  def create
    puts params
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @cocktail = @dose.cocktail
    @dose.destroy
    redirect_to cocktail_path(@cocktail)
  end

private

  def set_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/dose_helper.rb
module DoseHelper
end

app/helpers/ingredient_helper.rb
module IngredientHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors [:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<p id="notice"><%= notice %></p>
<h1>Cocktails#index</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
    </tr>
  </thead>


  <tbody>
    <%= @cocktails.each do |cocktail| %>
    <tr>
      <td><%= cocktail.name %></td>
      <td><%= link_to 'Show' %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<h1>New Cocktail</h1>


<%= render 'form', cocktail: @cocktail %>
<%= link_to 'Back', cocktails_path %>

app/views/cocktails/show.html.erb
<p id='notice'><%= notice %></p>

<p>
  <strong>Name: </strong>
  <%= @restaurant.name %>
</p>

<%= link_to "Add Dose", new_cocktail_dose_path(@cocktail) %>

<br>

<%= link_to 'Back', cocktails_path %>

app/views/dose/_form.html.erb
<%= simple_form_for(@dose) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors [:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<%= end %>

app/views/dose/new.html.erb
<h1>Add Dose</h1>



<%= render 'form', dose: @dose %>
<%= link_to 'Back', doses_path %>

app/views/doses/_form.html.erb
<%= simple_form_for(@dose) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors [:base].present? %>

  <div class="form-inputs">
    <%= f.input :description %>
  </div>

  <div class="form-inputs">
    <%= f.input :ingredient_id, collection: Ingredient.all %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/doses/create.html.erb
<h1>What Dose would you like to create for <%= @cocktail.name %></h1>

<%= simple_form_for [@cocktail, @dose] do |f| %>
  <%= f.input :description %>
<%= end %>

app/views/doses/new.html.erb
<h1>Add Dose</h1>


<%= render 'form', dose: @dose %>
<%= link_to 'Back', doses_path %>

app/views/ingredients/create.html.erb
<h1>Ingredient#create</h1>
<p>Find me in app/views/ingredient/create.html.erb</p>

app/views/ingredients/new.html.erb
<h1>Ingredient#new</h1>
<p>Find me in app/views/ingredient/new.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>